enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'rlib'

include ':rlib-common'
include ':rlib-fx'
include ':rlib-network'
include ':rlib-testcontainers'
include ':rlib-mail'
include ':rlib-logger-api'
include ':rlib-logger-impl'
include ':rlib-logger-impl-json'
include ':rlib-logger-slf4j'
include ':rlib-logger-slf4j-impl'
include ':rlib-plugin-system'
include ':rlib-geometry'
include ':rlib-classpath'
include ':rlib-compiler'
include ':rlib-io'
include ':rlib-collections'
include ':rlib-functions'
include ':rlib-reusable'
include ':rlib-reference'
include ':rlib-concurrent'
include ':rlib-eventbus'
include ':test-coverage'
