module com.ss.rlib {
    requires static java.compiler;
    requires static bonecp;
    requires annotations;
    requires java.management;
    requires java.sql;
    requires java.desktop;
    exports com.ss.rlib;
    exports com.ss.rlib.graphics.color;
    exports com.ss.rlib.plugin;
    exports com.ss.rlib.classpath;
    exports com.ss.rlib.compiler;
    exports com.ss.rlib.concurrent;
    exports com.ss.rlib.concurrent.executor;
    exports com.ss.rlib.concurrent.lock;
    exports com.ss.rlib.concurrent.task;
    exports com.ss.rlib.concurrent.atomic;
    exports com.ss.rlib.concurrent.deadlock;
    exports com.ss.rlib.concurrent.util;
    exports com.ss.rlib.data;
    exports com.ss.rlib.database;
    exports com.ss.rlib.function;
    exports com.ss.rlib.geom;
    exports com.ss.rlib.geom.bounding;
    exports com.ss.rlib.manager;
    exports com.ss.rlib.logging;
    exports com.ss.rlib.monitoring;
    exports com.ss.rlib.io;
    exports com.ss.rlib.util.ref;
    exports com.ss.rlib.util.random;
    exports com.ss.rlib.util.pools;
    exports com.ss.rlib.util.os;
    exports com.ss.rlib.util.linkedlist;
    exports com.ss.rlib.util.dictionary;
    exports com.ss.rlib.util.crypt;
    exports com.ss.rlib.util.array;
    exports com.ss.rlib.plugin.exception;
    exports com.ss.rlib.plugin.annotation;
    exports com.ss.rlib.network.server.client;
    exports com.ss.rlib.network.server;
    exports com.ss.rlib.network.packet;
    exports com.ss.rlib.network;
    exports com.ss.rlib.idfactory;
}