plugins {
  id("configure-java")
  id("configure-publishing")
}

dependencies {
  api projects.rlibCommon
  api projects.rlibClasspath
  api projects.rlibCollections
  api projects.rlibReusable
  api libs.project.reactor.core
  testRuntimeOnly projects.rlibLoggerImpl
  loadTestRuntimeOnly projects.rlibLoggerImpl
  testImplementation testFixtures(projects.rlibCommon)
}
