plugins {
  id("configure-java")
  id("jacoco-report-aggregation")
}

dependencies {
  jacocoAggregation projects.rlibClasspath
  jacocoAggregation projects.rlibCollections
  jacocoAggregation projects.rlibCommon
  jacocoAggregation projects.rlibConcurrent
  jacocoAggregation projects.rlibFunctions
  jacocoAggregation projects.rlibGeometry
  jacocoAggregation projects.rlibIo
  jacocoAggregation projects.rlibLoggerApi
  jacocoAggregation projects.rlibLoggerImpl
  jacocoAggregation projects.rlibLoggerSlf4j
  jacocoAggregation projects.rlibLoggerSlf4jImpl
  jacocoAggregation projects.rlibLoggerImplJson
  jacocoAggregation projects.rlibMail
  jacocoAggregation projects.rlibNetwork
  jacocoAggregation projects.rlibPluginSystem
  jacocoAggregation projects.rlibReference
  jacocoAggregation projects.rlibReusable
  jacocoAggregation projects.rlibEventbus
  jacocoAggregation projects.rlibTestcontainers
}
